In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3135, 3892, 8671, 7566],
 [3135, 3892, 8671, 1157],
 [3135, 671, 8671, 996],
 [654, 224, 9066, 9687, 7492],
 [654, 224, 9066, 9687, 6877],
 [7361, 3135, 1762, 8671, 4611],
 [3204, 2252, 8387, 9687]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3135 3892 8671 7566]
 [   0    0    0    0 3135 3892 8671 1157]
 [   0    0    0    0 3135  671 8671  996]
 [   0    0    0  654  224 9066 9687 7492]
 [   0    0    0  654  224 9066 9687 6877]
 [   0    0    0 7361 3135 1762 8671 4611]
 [   0    0    0    0 3204 2252 8387 9687]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 105ms/step


array([[[ 0.04720911, -0.04271227, -0.04118724, -0.00653113,
          0.00919922, -0.02035741, -0.03642026, -0.04189695,
          0.01489704, -0.01327496],
        [ 0.04720911, -0.04271227, -0.04118724, -0.00653113,
          0.00919922, -0.02035741, -0.03642026, -0.04189695,
          0.01489704, -0.01327496],
        [ 0.04720911, -0.04271227, -0.04118724, -0.00653113,
          0.00919922, -0.02035741, -0.03642026, -0.04189695,
          0.01489704, -0.01327496],
        [ 0.04720911, -0.04271227, -0.04118724, -0.00653113,
          0.00919922, -0.02035741, -0.03642026, -0.04189695,
          0.01489704, -0.01327496],
        [ 0.02213398, -0.02127135,  0.02708865, -0.04747555,
         -0.00415214, -0.04665393, -0.00910621,  0.00765624,
          0.03266824, -0.0447483 ],
        [-0.02431594,  0.03171413,  0.02827403,  0.02710679,
         -0.01404453,  0.00704367,  0.0443373 , -0.00027869,
         -0.02884971, -0.00218226],
        [-0.00635599,  0.04605135,  0.02469215, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3135, 3892, 8671, 7566])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 80ms/step


array([[ 0.04720911, -0.04271227, -0.04118724, -0.00653113,  0.00919922,
        -0.02035741, -0.03642026, -0.04189695,  0.01489704, -0.01327496],
       [ 0.04720911, -0.04271227, -0.04118724, -0.00653113,  0.00919922,
        -0.02035741, -0.03642026, -0.04189695,  0.01489704, -0.01327496],
       [ 0.04720911, -0.04271227, -0.04118724, -0.00653113,  0.00919922,
        -0.02035741, -0.03642026, -0.04189695,  0.01489704, -0.01327496],
       [ 0.04720911, -0.04271227, -0.04118724, -0.00653113,  0.00919922,
        -0.02035741, -0.03642026, -0.04189695,  0.01489704, -0.01327496],
       [ 0.02213398, -0.02127135,  0.02708865, -0.04747555, -0.00415214,
        -0.04665393, -0.00910621,  0.00765624,  0.03266824, -0.0447483 ],
       [-0.02431594,  0.03171413,  0.02827403,  0.02710679, -0.01404453,
         0.00704367,  0.0443373 , -0.00027869, -0.02884971, -0.00218226],
       [-0.00635599,  0.04605135,  0.02469215, -0.03040257,  0.00833731,
        -0.01849415,  0.03935324,  0.03185768